//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_adress
    {
        public int Id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Addres_id { get; set; }
    
        public virtual Address_c Address_c { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
