//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatives
    {
        public int Id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public string PIB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Who_for_customer { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
